fix(win): Fix occasional buffer overflows (#166)
This fixes a problem I have had where I get the following message sometimes:
Error: config, windows: The file name is too long.

Delv says it is a buffer overflow so this fixes it at the cost of just allocating more memory.

TODO: Make actually good

Reviewed-on: https://git.froth.zone/sam/awl/pulls/166
Reviewed-by: grumbulon <grumbulon@grumbulon.xyz>